### ISSUE TITLE
i wants thy current setup, where is it, skimmed thru ur dotfiles, but it was eww

### ISSUE THREAD

**Issue by daUnknownCoder** [T0kyoB0y/PotatoWidgets#1]

**Comment by 1e165** [comment]
?

**Comment by daUnknownCoder** [comment]
> ?

talking abt:
[img3](https://github.com/T0kyoB0y/PotatoWidgets/blob/main/img/setup3.png)
[img2](https://github.com/T0kyoB0y/PotatoWidgets/blob/main/img/setup2.png)
[img](https://github.com/T0kyoB0y/PotatoWidgets/blob/main/img/setup.png)

**Comment by daUnknownCoder** [comment]
came from hyprland discord he had posted this rice there...

**Comment by 1e165** [comment]
> came from hyprland discord he had posted this rice there...

why didn't you just DM then?

**Comment by daUnknownCoder** [comment]
> > came from hyprland discord he had posted this rice there...
> 
> why didn't you just DM then?

i did but havent got a reply... [discord thread link](https://discord.com/channels/961691461554950145/1212542925745946724/1215026066310299788)

**Comment by tokyob0t** [comment]
Hello @daUnknownCoder  ! The reason I haven't posted my setup is that I've been continuously implementing functionalities (Services) into this project. Since my setup consists of patches of code here and there, I don't recommend using it because ultimately, all the features of my setup will be added to this Python library. For example, the notifications daemon, the application launcher, etc., whose examples you can find [here](https://github.com/T0kyoB0y/PotatoWidgets/wiki/Examples).

**Comment by daUnknownCoder** [comment]
I understand @T0kyoB0y, but the reason I'm looking for your dots is because b4 I saw ur setup I was going to become an AGS dev by creating windows things using AGS but the I saw ur setup so I wanted ti see how are u doing it...

**Comment by tokyob0t** [comment]
finally updated my dotfiles
https://github.com/T0kyoB0y/dotfiles/tree/hyprland-potato
